Feat authentication page
surajmore98/E-commerce pull request #3
Opened 2022-02-12 17:10 UTC by surajmore98

pages added.
- register
- sign-in
- logout

Login Page

![image](https://user-images.githubusercontent.com/29055479/153766566-b3e49da3-4a47-4c35-a15f-358ae43dedab.png)

Logout Page

![image](https://user-images.githubusercontent.com/29055479/153766592-98dc1e6b-ee65-4c16-9aeb-73bde70acb28.png)

Register Page

![image](https://user-images.githubusercontent.com/29055479/153766662-eb0f4034-3e9e-4e58-8ead-0a86b7f1b128.png)

2022-02-12 18:01 UTC, shrey27 commented on src/cart.html
> +        <link rel="stylesheet" href="./style/cart.css"/>
add styles in common styles file and import the file itself

2022-02-12 18:05 UTC, shrey27 commented on src/style/wishlist.css
> +}
Just a suggestion. try to go with mobile first styling, that way code will be better structured, less breakpoints will be needed and you can catch the styling errors in early stages.

2022-02-12 18:05 UTC, shrey27 approved these changes

2022-02-13 16:55 UTC, surajmore98 commented on src/cart.html
> +        <link rel="stylesheet" href="./style/cart.css"/>
Thanks for catching, will do it in next PR for all.

2022-02-13 17:25 UTC, ddivyansh18 requested changes

2022-02-13 17:25 UTC, ddivyansh18 commented on src/logout.html
> +    </div>
It should say "You are logged out"

2022-02-13 17:27 UTC, surajmore98 commented on src/logout.html
> +    </div>
@ddivyansh18  done.

2022-02-13 17:28 UTC, ddivyansh18 approved these changes
Looks good to merge now !

2022-02-13 17:29 UTC, merged